ui/src/nav/Help.tsx
The original Foundation group which is referenced here has been archived now that we've moved to the new one on ~halbex-palheb.
=> update foundation group

ui/src/preferences/SystemPreferences.tsx, ui/src/styles/grids.css
Changes the max-height of the aside and main sections to match the height of the modal itself. Also adds a media query to fix a mobile regression.
A quick demo:
https://user-images.githubusercontent.com/748181/208215555-13d42ea7-9400-4de9-b7d9-054d9d3f861c.mov
=> landscape: fix system preferences scrolling

ui/src/components/AppInfo.tsx
Copy button uses the new app ref schema (`/1/desk/ship/desk`) for easy paste-ability in Groups 2
=> grid: update app ref

desk/desk.docket-0, ui/src/components/ErrorAlert.tsx, ui/src/preferences/SystemPreferences.tsx, ui/src/preferences/about-system/AboutSystem.tsx
- Recognize if a kelvin update failed and present a "retry" button.
- Recognize if that failure was due to an out-of-date binary and instruct the user to update their binary.
- Disallow system updates if grid is blocked, and inform the user.
- Update copy throughout system update page to be more consistent and clear.
- Change the displayed name from "System" to "Grid".  "System" was ambiguously used for %garden and %base, and this caused no end of confusion.
- Update the "submit issue" link target from urbit/landscape (doesn't exist) to tloncorp/landscape-apps
Paired with @zalberico to make these changes.  I tried to match the JS style to the surrounding code, I have no opinion on how it's factored.
This shows most of the error states you could hit (I don't show the success at the end …
=> Handle kelvin update error cases

desk/desk.docket-0, ui/src/preferences/about-system/AboutSystem.tsx
In "Installed App Settings" change the name of the App Launcher from Grid to Landscape.
This PR also updates the kelvin update copy for the case when Landscape is blocking base from updating.
=> preferences: rename grid to landscape in sidebar and update copy

.github/workflows/bump.yml
fixes sed syntax and and adds a commit message so it doesn't trigger the deploy action
=> ops: fix version bump action

ui/src/preferences/SecurityPrefs.tsx, ui/src/preferences/SystemPreferences.tsx, ui/src/tiles/Tile.tsx, ui/src/tiles/TileMenu.tsx
- Moves logout to its own pane instead of a modal (fixes tloncorp/landscape-apps#1441)
- Adds mobile-specific event-bubbling for the app tile dropdown menu (fixes tloncorp/landscape-apps#1371)
- Dims and grayscales tiles corresponding to suspended desks (fixes #15)
=> garden: various maladies

desk/app/docket.hoon
See tloncorp/landscape-apps#1771.
This fixes that issue for affected ships.  We check the current source for %talk and %groups, and if it's not a moon, then we set it to the correct ships.  If it is a moon, we assume that either the ship is unaffected or they intended to set it to something specific (eg to a prerelease moon).
=> docket: fixup %talk and %groups sources

ui/src/state/util.ts
Brings the profile color into parity with Groups and Talk, fixes #96.
Groups:
Landscape:
=> landscape: fix normalizeUrbitColor

ui/src/components/AppInfo.tsx, ui/src/components/Dialog.tsx, ui/src/components/LandscapeWayfinding.tsx, ui/src/preferences/about-system/AboutSystem.tsx
This changes how we do dialogs that stack. Previously radix UI did this work for us, but they removed this behavior in the updated version because it was probably too complicated on their end. This changes the two places we use stacked dialogs to manually change the z-indexes so they stack appropriately, restoring the missing suspend button.
=> dialog: fixing usage across stacking dialogs

ui/src/components/LandscapeWayfinding.tsx, ui/src/nav/Nav.tsx, ui/src/pages/Grid.tsx
This makes a small adjustment to the wayfinding button so it aligns a little better. Notably this makes the get urbit apps button look more like a search bar on mobile, but that makes the wayfinding button feel like it's not floating arbitrarily up.
**before**
**after**
=> wayfinding: placement

ui/src/components/LandscapeWayfinding.tsx, ui/src/nav/Nav.tsx, ui/src/pages/Grid.tsx
Discussed out of band with @urcades. Places the wayfinding bug inline with the other nav elements on mobile, shifts it to fixed-position for wider viewports.
=> landscape: place and size wayfinding bug

ui/src/components/LandscapeWayfinding.tsx
Fell victim to the `space-x-2` rule in the parent nav component, thus the `!` important.
=> landscape: kill left-margin on wayfinding button

ui/src/constants.ts
This addresses feedback from the Goals team (~niblyx-malnus and ~sidlup-havwen):
> very nice surprise to see Goals listed in the new app installation feature of landscape! thanks! :)
> **sidlup-havwen** did notice that it does seem to redirect to `/app/goals` , though, when it should (for historical reasons) actually redirect to [...] `/apps/gol-cli`
=> apps: update Goals path in suggestions

ui/src/logic/utils.ts
fixes #125 
I wasn't able to reproduce the exact issue in #125, but I think this was actually what the user was seeing.
We were firing off a test notification each time the count or unreadNotifications changed, along with the real notification itself.
We also weren't properly including notification content (DMs or mentions would just show that you got a DM or a mention, but not the content of the message). This fixes that.
=> notifications: fix duplicate notification issue

ui/src/state/hark-types.ts
Fixes #140.
We didn't check whether the object actually existed in isYarnShip and isYarnEmph.
=> Fix for 'emph' issue in notification

ui/src/tiles/TileGrid.tsx
This introduces some padding to the bottom of the grid. Before this change, the bottom of the grid was aligned to the bottom of the scrollable view
Scrolled to the bottom:
=> ui: increase spacing at bottom of grid

ui/src/preferences/StoragePrefs.tsx
Intended to address #170
- **Changes input type of endpoint field to `url`** which should help hint to browsers what kind of value is expected.
- **Adds `spellcheck="false"` to Access Key fields** which are extremely unlikely to have spellcheck-able input. Does not set "off" for bucket name or regions which may have inputs that you'd want to spellcheck. Personally, I'm not confident enough to turn it off for that reason.
- **Adds `autocorrect="off"` to all fields** this is a Safari extension, but other browsers may respect it as well. I think it's often-enough unhelpful for fields like this that disabling it is safe.
⚠️ I am not sure I set up the `landscape` dev environment 100% correctly, and when I test this locally with the vite proxy through `npm run dev` all the inputs on this …
=> settings: disable autocorrect and spellcheck on s3 settings inputs

ui/src/nav/notifications/Notification.tsx
Adds a regular expression to add `break-all` to URLs in notifications. This works with `line-clamp` to truncate the URL and avoid the scroll-overflow seen in #190. 
Also checks for `@p`s and uses the `ShipName` component in the message text to support nicknames.
fixes #190
=> notifications: breaks URLs in notification text, uses shipname

desk/app/vitals-tester.hoon, desk/app/vitals.hoon, desk/desk.bill, desk/lib/vitals.hoon, desk/mar/vitals/qos.hoon, desk/mar/vitals/result.hoon, desk/sur/vitals.hoon, desk/ted/vitals/connection-check.hoon
All pokes, scries, subscriptions, and Arvo results have been tested. Every connectivity success and failure case in the thread has been tested. Tests were performed using fake ships and local networking.
The only potential issue I noticed during testing is that Ames doesn't have any state for ships with which our ship has never attempted to communicate, and this results in scries to Ames for `ship-state` to crash. If this becomes an issue, we can workaround it by reordering operations in the connectivity check thread: send a `|hi` to the target immediately, wait until timeout, and then later re-check the Ames state. Any attempted communication - even a failed or incomplete `|hi` - resolves this Ames scry crash.
Next steps for improving performance / correctness are included in the …
=> vitals: initial commit of connectivity check agent

ui/src/constants.ts
Humbly request adding Trill, now integrating Tlon Chat and Pals, to the list of recommended apps in Garden.
Now that Twitter operations are tumbling it's good timing to remind people of just how smooth Urbit is at running social media apps. Trill now has Global Feeds which aid greatly in content and user discovery in the network.
=> added Trill to app recommendation list

desk/app/treaty.hoon, ui/src/app.tsx, ui/src/components/AppInfo.tsx, ui/src/constants.ts, ui/src/gear/hark/types.ts, ui/src/logic/useReactQuerySubscribeOnce.ts, ui/src/logic/utils.ts, ui/src/nav/notifications/Notification.tsx, ui/src/nav/search/Home.tsx, ui/src/nav/search/TreatyInfo.tsx, ui/src/state/bootstrap.ts, ui/src/state/docket.ts, ui/src/state/hark.ts, ui/src/state/watcher.ts, ui/src/tiles/RemoveApp.tsx, ui/src/tiles/SuspendApp.tsx, ui/src/tiles/TileMenu.tsx, ui/src/window.ts
new version of @patosullivan 's PR #192 with latest develop and updated for changes to [tloncorp/landscape#2574](https://github.com/tloncorp/landscape-apps/pull/2574)
> Adds a mutation to create a yarn from the frontend.
Adds a new zustand state for tracking actions that could take a while (WatcherStore).
Switches docket over to react-query (added a new scry endpoint as part of this).
Adds a bootstrap script that we can start to use incrementally.
Fixes a misspelling in constants for the ship hosting Quorum.
Fixes some type issues around the new Yarn type.
Closes https://github.com/tloncorp/landscape/issues/154
Fixes LAND-505
This is dependent on https://github.com/tloncorp/landscape-apps/pull/2574
=> docket: notify on long-running app install

ui/src/components/LandscapeWayfinding.tsx, ui/src/nav/Help.tsx
Just noticed that the wayfinding helper references Tlon Public instead of Tlon Local; this fixes that.
=> update wayfinding to reference Tlon Local

desk/app/bark.hoon, desk/ted/save-summary.hoon
We weren't accounting for the different wire used for this, causing us to spill our spaghetti and redirect processing to `+on-fail`, which wasn't very graceful.
This didn't impact the threads/functionality itself, only bark's non-existent bookkeeping. The crash went into `+on-fail`, which was crashing in turn.
With this change, we can actually properly notify (in the terminal (; ) on failed thread runs.
=> bark: correctly handle save-summary thread results

desk/lib/summarize.hoon
There is a (somewhat poorly understood, cc @arthyn: thoughts?) case where the group associated with a chat may not actually contain that chat in its channels listing.
Here, instead of assuming the channel is always present, we ask for it more gently, and simply skip to the next-most-active channel if it turns out to be missing.
We also remove a stray debug printf, and add a trace print in case anything else goes wrong here.
=> lib: avoid crash during activity summarization

desk/ted/save-summary.hoon
The "save summary" thread still had hark flagged as one of its dependencies, but doesn't actually use that for anything anymore.
Here we simply remove the import.
(Already hand-deployed onto the bark service ship, no particular rush in getting this out.)
=> bark: remove /sur/hark dependency from thread

ui/src/logic/utils.ts, ui/src/nav/Hosting.tsx, ui/src/nav/Nav.tsx, ui/src/preferences/SystemPreferences.tsx
Adds a button in the header for hosted ships to get to their Horizon panel.
When clicked:
Also adjusts the "Get Urbit Apps" button to match in dark mode (was annoying me).
Fixes tloncorp/ylem#1506
=> landscape: add tlon hosting linkback

ui/src/nav/Hosting.tsx
Follow up to https://github.com/tloncorp/landscape/pull/212
Modifies the linkback from `/login` to `/dashboard` to aid with how redirects are handled by https://github.com/tloncorp/ylem/issues/1508 and remove an extra click from https://github.com/tloncorp/ylem/pull/1648 for users who are heading directly to the dashboard.
=> landscape: modify tlon hosting linkback from /login -> /dashboard

desk/lib/groups-json.hoon, desk/lib/hark-json.hoon
This fixes LAND-849 by properly copying the dejs function for nests. Also updates the json lib to match what was in groups.
=> hark: bad copy from groups

ui/src/state/vere.ts
The path format is now different because it includes the pace of the runtime (edge, soon or live). See https://github.com/urbit/vere/pull/473.
=> vere: fix vere version check for 412k

desk/app/bark.hoon, desk/app/growl.hoon, desk/ted/mailchimp/update-merge-fields.hoon, desk/ted/save-summary.hoon
Previous logic for reading `%settings-event` facts was a little too eager
in declaring explicit non-consent. It would also set the flag to false
in cases where we received updates not matching what we were looking
for.
Now, it's not entirely certain that this was a problem, but we did
observe "disabled growl" on ships that had the setting toggle on the
frontend set to true, and this seemed like the only viable cause of
that.
We also update +on-load to re-set the flag from the current settings
value, to correct any lingering mismatching states.
We may want to make an additional, largely unrelated change to bark that should go out alongside this, but discussion pending. See also COMMS-242.
=> growl: don't fumble the activity logging consent

desk/app/growl.hoon
The upgrade from `%0` to `%1` was calling into `+on-init`, which issues a scry. In some cases, that might not be able to complete successfully, aborting the whole event that triggered the load.
Here, we move this "set flag based on settings" logic into a `%default` poke command, and change the `+on-load` logic to set a timer that calls that instead, deferring the scry to the next event.
My humble apologies for violating the now age-old rule of not scrying during load. Anyone who failed to apply the OTA because of this will still be on `%0`, be able to apply this patch successfully, and end up in the same good state that most people should already be. People who already applied the OTA are unaffected.
=> growl: don't scry during +on-load

ui/src/preferences/SystemPreferences.tsx, ui/src/state/vere.ts
This fixes LAND-1027 by making sure we parse the version strings the same way, and uses a more reliable method. Also unfilters Landscape from the sidebar so people can see their OTA source and change it.
=> system preferences: fix vere version parsing

desk/app/genuine.hoon
We were seeing intermittent mismatches when reading the %genuine secret from the URL. After testing, they went away with this change.
=> Remove dots from serialized %genuine secret

desk/app/storage.hoon, desk/lib/storage-json.hoon, desk/sur/storage-1.hoon, ui/src/gear/storage/lib.ts, ui/src/gear/storage/types.ts, ui/src/preferences/StoragePrefs.tsx, ui/src/state/storage/reducer.ts, ui/src/state/storage/storage.ts, ui/src/state/storage/upload.ts
From @arthyn: This fixes LAND-999 by adding new state to the %storage backend and allows hosting users to customize whether they want to use Tlon provided presigned URLs or their own custom credentials for direct S3 uploads.
Similar changes are being pulled into the Tlon app here: https://github.com/tloncorp/landscape-apps/pull/2906
=> storage: add token-based upload for hosting

ui/src/env.d.ts, ui/src/logic/utils.ts, ui/src/state/storage/reducer.ts, ui/src/state/storage/storage.ts
This matches https://github.com/tloncorp/landscape-apps/pull/2973 so that hosted ships see their toggle in the correct state even if they don't actually have a presigned URL set in their storage state.
=> storage: hardcode url to mimic groups

desk/mar/contact.hoon
This fixes an issue found by @alecananian where our contact mark wasn't compiling. I don't think this was used on the frontend previously which is likely why.
=> contacts: fixing bad mark

ui/src/constants.ts
Updates the `%blog` listing in the Get Urbit Apps menu from the defunct %blog at `~hanrut-sillet-dachus-tiprel/blog` to Common Blog on `~dister-bonbud-macryg/blog`.
=> Replace %blog listing with Common Blog

desk/lib/summarize.hoon, desk/sur/channels.hoon, desk/sur/chat-2.hoon, desk/sur/chat.hoon
`/lib/summarize` now supports building summaries off of the new `/app/channels`. If that agent is running, it will use the new summarization logic. If it's not, it will continue on as it has.
Somewhat important to get this out the door ahead of the new groups backend release. If a ship uses the old version of this library while the new groups backend is installed, summarization logic may crash. In practice, this probably only affects reports for %bark. (But third-party devs using this library are encouraged to pull in this latest version also.)
Also pulls in the necessary sur file dependencies. If those change, in particular the ones including types we scry for, we may need to update the files here again. (One such change is probably on the way, we may want to hold off on merging for at …
=> lib: support summarization of new groups backend

desk/app/docket.hoon
Handles URL encoding special characters on the docket upload side, and when retrieving files from the glob.
cc: @arthyn @Fang- 
Expedited review/deploy would be helpful, this is blocking third party integrations
=> docket: fix URL encoding handling

desk/app/contacts.hoon
And, crucially, re-establish subscriptions in the cases that got broken by the poor %kick handling. These are cases where we think %chi (subscription established), but there is no matching subscription to be found in the bowl.
Setting `sag` to `~` prior to calling into `+si-heed` again is the minimally viable fix here. I would rather rip out that state entirely, but that's a bigger lift.
Tested on palfun, fixed the cases I had observed on it, magically pulled in the freshest profile data.
Fixes LAND-1407, or at least its common cause.
=> contacts: fix %kick handling

ui/src/nav/notifications/Notification.tsx
Fixes an issue reported by ~nallux-dozryl where trying to make a notification resulted in a crash
=> notification: prevent notification with single piece of content from crashing

desk/app/docket.hoon
`/app/docket` was failing to compile. `+fip` is no longer a parser, but we were still calling it as such.
Presumably introduced in #245, which is weird, because I'm pretty sure we ran the code there locally at the time.
=> docket: call +fip appropriately

desk/app/vitals.hoon, desk/lib/vitals.hoon, desk/ted/vitals/connection-check.hoon
Includes the following fixes (which allow this thread and the associated app to be used trivially on fake ships/networks):
- skip sponsor checks for galaxies (avoids a crash in /app/vitals/hoon)
- mark peers unknown to %ames as %dead (avoids [a crash in /ax/peers/...](https://docs.urbit.org/system/kernel/ames/reference/scry#peers[ship]))
- change thread input from `@p` to `(unit @p)` (allow [calling from dojo](https://docs.urbit.org/userspace/threads/tutorials/basics/fundamentals#a-trivial-thread))
Only tested locally with the following manual test algorithm:
1. With `~zod` and `~nec` live on a local network (with no prior communications between them), run the following on `~zod`:
```
:vitals &run-check ~nec
```
2. Wait a few seconds and then run the following on `~zod` and verify a …
=> patch many minor issues with `vitals/connection-check.hoon` thread

ui/src/constants.ts
The previous icon is a 404 now
=> Fix %radio icon in suggested apps

desk/app/docket.hoon
It was deprecated in favor of %landscape, but is still active on people's ships and blocking the 411 update. Here, we make docket suspend the %garden desk unconditionally.
Debated deferring this to a separate event, since it may kick off the base update, but the suspension itself should isolate that into its own separate event already.
=> docket: suspend the %garden desk

desk/sur/vitals.hoon, desk/ted/vitals/connection-check.hoon
411 introduces informal pings where the NAT pinhole is kept open through vere instead of a formal ames message. This breaks vitals.
This PR fixes the problem and is also compatible with 412.
```
> -landscape!vitals-connection-check ~zod
[%yes ~]
```
The green/yellow/red balls in groups are also fixed by this one. Tested on my own livenet ship.
=> vitals: fix vitals to support 411 informal pings
