tloncorp/landscape

ui/src/state/settings.ts

this shouldn't be true by default lol

garden: changed initial do not disturb state to false

---

ui/src/tiles/TileGrid.tsx

grid: removing old groups filter

---

ui/src/nav/Nav.tsx

OTT, addresses tloncorp/landscape-apps#938

nav: restore james' orb

---

ui/package-lock.json
ui/package.json
ui/public/mockServiceWorker.js
ui/src/components/icons/SlidersIcon.tsx
ui/src/preferences/StoragePrefs.tsx
ui/src/preferences/SystemPreferences.tsx
ui/src/state/storage-reducer.ts
ui/src/state/storage.ts

Moves S3 settings from Groups 1 to a tab in the Landscape system preferences. Addresses tloncorp/landscape-apps#930

s3-store: moves storage settings

---

ui/src/preferences/StoragePrefs.tsx
ui/src/state/storage-reducer.ts
ui/src/state/storage.ts

OTT
Corresponding urbit/urbit PR: https://github.com/urbit/urbit/pull/6051

Add region to s3 settings

---

ui/public/mockServiceWorker.js
ui/src/components/Avatar.tsx

avatar: proper aspect ratio

---

ui/src/nav/Leap.tsx
ui/src/preferences/AppearancePrefs.tsx
ui/src/preferences/NotificationPrefs.tsx
ui/src/preferences/SystemPreferences.tsx

copy: fixed appearance and notification typos

---

ui/src/logic/useSystemUpdate.tsx

This resolves https://github.com/tloncorp/landscape-apps/issues/1337 by importing remaining desk changes from urbit/urbit/pkg/grid

grid: only block on live apps

---

desk/app/docket.hoon

docket: drop charges if no docket file

---

ui/public/mockServiceWorker.js
ui/src/nav/notifications/Notification.tsx
ui/src/nav/notifications/Notifications.tsx
ui/vite.config.ts

see: #1549.
the "visibilitychange" listener was waiting for a visibility change to run, which doesn't make sense if the page is already open and someone hits the button.
also fixes missing key console warning in `Notification`

notifications: clear notifications on pressing button

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/actions/deploy/Dockerfile
.github/actions/deploy/action.yml
.github/actions/deploy/entrypoint.sh
.github/actions/release/Dockerfile
.github/actions/release/action.yml
.github/actions/release/entrypoint.sh
.github/workflows/bump.yml
.github/workflows/deploy-canary.yml
.github/workflows/deploy-external.yml
.github/workflows/deploy-internal.yml
.github/workflows/deploy-live.yml
.github/workflows/deploy.yml

ops: adding github flows

---

ui/src/nav/notifications/Notifications.tsx

see: tloncorp/landscape-apps#1265.

garden: mark notification read button

---

ui/src/nav/Nav.tsx

fixes tloncorp/landscape-apps#1372

garden: close system preferences menu

---

ui/src/nav/Leap.tsx

fixes tloncorp/landscape-apps#1373

garden: 16px font size for leap on mobile

---

ui/.gitignore
ui/package-lock.json
ui/package.json
ui/public/mockServiceWorker.js
ui/src/components/Avatar.tsx
ui/src/components/GroupAvatar.tsx
ui/src/components/ShipName.tsx
ui/src/components/icons/ColorBoxIcon.tsx
ui/src/logic/useMedia.ts
ui/src/nav/notifications/Notification.tsx
ui/src/nav/notifications/Notifications.tsx
ui/src/nav/notifications/groups.ts
ui/src/state/avatar.ts
ui/src/state/settings.ts
ui/src/state/util.ts
ui/src/styles/base.css
ui/tailwind.config.js

- Refactors the Notification component significantly and adds more display logic
- Adds several components and state logics we used in tloncorp/landscape-apps
- Brings the ShipName and Avatar components up to date, using data from contact-store and respecting calmengine settings
fixes tloncorp/landscape-apps#1689

garden: new notifications

---

README.md
ui/src/nav/notifications/Notification.tsx

Fixes an issue where new notifications were unreadable in dark mode.

notifications: fix mix-blend mode for dark mode

---

ui/src/state/hark.ts

OTT, fixes issue @zalberico saw where notifications ends up empty

hark: expects ud in quilt scry

---

ui/package-lock.json
ui/package.json
ui/src/app.tsx
ui/src/components/Dialog.tsx
ui/src/components/GroupLink.tsx
ui/src/components/LandscapeWayfinding.tsx
ui/src/nav/Help.tsx
ui/src/pages/Grid.tsx
ui/src/preferences/AttentionAndPrivacy.tsx
ui/src/state/settings.ts
ui/src/styles/components.css
ui/src/tiles/TileGrid.tsx
ui/tailwind.config.js

Fixes https://github.com/tloncorp/landscape-apps/issues/1856 for landscape itself.
Includes new calm engine pref for showing/hiding the wayfinding toggle.
Also cleaned up the Help & Support section of system prefs, removed the link to rondev's group discovery group and replaced it with a link to Tlon Public.

Add wayfinding to Landscape, clean up Help & Support

---

ui/src/components/AppInfo.tsx
ui/src/components/ErrorAlert.tsx
ui/src/components/LandscapeWayfinding.tsx
ui/src/nav/Nav.tsx
ui/src/nav/SystemMenu.tsx
ui/src/pages/Grid.tsx
ui/src/preferences/about-system/AboutSystem.tsx
ui/src/tiles/RemoveApp.tsx
ui/src/tiles/SuspendApp.tsx
ui/src/tiles/TileMenu.tsx

Fixes issues related to updating dropdown/dialog packages from radix-ui.
This will fix the broken build on master.

Update uses of Dropdown and Dialog from radix to conform with upgrade

---

ui/src/main.tsx

OTT, this follows the update of urbit/urbit#5918 fixing #82

auth: switch to new compatibility method

---

ui/src/tiles/TileMenu.tsx

tile-menu: fix app info and make targets bigger

---

ui/src/tiles/TileMenu.tsx

tile-menu: portal menu and fix resume option

---

ui/src/app.tsx
ui/src/logic/utils.ts
ui/src/nav/notifications/Notification.tsx
ui/src/nav/notifications/useNotifications.ts
ui/src/preferences/NotificationPrefs.tsx
ui/src/state/hark-types.ts

If the user has already given us permission to show them notifications and we have some unreads, send the notification.

bring back browser notifications

---

ui/src/app.tsx

OTT, so we can not worry about when the nav change on the other side gets deployed

routes: retain old route for compat

---

ui/public/mockServiceWorker.js
ui/src/app.tsx
ui/src/logic/utils.ts

OTT this prevents an issue with mobile clients not supporting old style browser notifications. We have to put this out with 1.7 or people won't be able to use on mobile.

app: prevent notification errors mobile

---

ui/src/constants.ts

fixes tloncorp/landscape-apps#2219

landscape: fix Quorum app link

---

ui/src/preferences/SystemPreferences.tsx
ui/src/state/invites.ts

Fixes https://github.com/tloncorp/lure/issues/52

Always show invite link settings

---

ui/src/preferences/InvitePrefs.tsx
ui/src/state/invites.ts

Fixes https://github.com/tloncorp/lure/issues/50

Add trailing slash to bait server automatically

---

ui/src/nav/AppSearch.tsx

app-search: allow distros longer than a planet

---

desk/app/reel.hoon

https://github.com/tloncorp/landscape-apps/pull/2444

Show lure connection issue

---

desk/app/settings.hoon
desk/app/storage.hoon
ui/src/state/settings.ts

settings: wrong mark

---

ui/src/api.ts
ui/src/app.tsx
ui/src/components/Avatar.tsx
ui/src/components/Button.tsx
ui/src/logic/useMedia.ts
ui/src/logic/useReactQueryScry.ts
ui/src/logic/useReactQuerySubscription.ts
ui/src/logic/utils.ts
ui/src/nav/notifications/Notifications.tsx
ui/src/nav/notifications/groups.ts
ui/src/state/scheduler.ts
ui/src/styles/components.css

This addresses #75 and also throws in some cleanup of the notifications modal, load order, and using the correct groups scry.

notifications: making progress indicator better

---

desk/ted/reel/set-ship.hoon

https://github.com/tloncorp/ylem/issues/1303#issuecomment-1536149205

Update reel set-ship URL

---

ui/src/nav/Nav.tsx
ui/src/preferences/about-system/AboutSystem.tsx
ui/src/state/vere.ts

Depends on https://github.com/urbit/urbit/pull/6629.

landscape: complain if vere is out of date

---

desk/mar/run-check.hoon
desk/mar/vitals/result.hoon
ui/package-lock.json
ui/src/components/ShipConnection.tsx
ui/src/gear/docket/types.ts
ui/src/gear/hood/types.ts
ui/src/logic/utils.ts
ui/src/nav/search/Apps.tsx
ui/src/nav/search/Home.tsx
ui/src/nav/search/TreatyInfo.tsx
ui/src/state/docket.ts
ui/src/state/vitals.ts
ui/src/styles/base.css
ui/src/tiles/Tile.tsx
ui/src/tiles/TileStatusIndicator.tsx

This adds the functionality in LAND-509 and improves app search as well by adding connection checking to all places where we're trying to communicate to another ship during the app install flow.
https://github.com/tloncorp/landscape/assets/5466421/d842e358-af2f-46c3-8a51-8d56dbb98d43
https://github.com/tloncorp/landscape/assets/5466421/2a0eb105-4365-44fc-85c3-c3fe8a43815c
fixes LAND-509

vitals: add new connection check to frontend and improve treaty fetch

---

desk/lib/storage-json.hoon
ui/src/gear/storage/types.ts
ui/src/state/storage/storage.ts

storage: use correct keys

---

ui/src/components/ShipConnection.tsx
ui/src/nav/search/Apps.tsx

app-search: show connection issues when finished

---

ui/src/preferences/StoragePrefs.tsx

storage: show loading spinner while loading storage settings

---

.github/workflows/deploy-kernel.yml

ops: allow kernel update deploys for testing

---

ui/package-lock.json
ui/package.json
ui/src/components/ShipCode.tsx
ui/src/logic/utils.ts
ui/src/preferences/about-system/AboutSystem.tsx
ui/src/state/code.ts

Adds an "Access Key" section to the About System preference pane.
When clicked:
Fixes LAND-936

landscape: add Access Key reveal/copy function

---

ui/src/preferences/SystemPreferences.tsx

sys-prefs: hide garden

---

desk/desk.docket-0

OTT, I know I changed this, but github doesn't show it in history 🙃

docket: bad base

---

ui/src/constants.ts

This adds Portal to our recommended apps list

apps: add portal to app list

---

desk/app/genuine.hoon
desk/desk.bill

https://linear.app/tlon/issue/LAND-1000/s3-create-urbit-side-secret-for-tlon-hosting
New %genuine agent that creates a secret stored on your ship. Usage: scry secret from the frontend at `/secret` and pass it to hosting S3 or other services. Then that service can check `[ship.tlon.network]/genuine/[secret]` and get either json `true` or json `false` for a successful or failed match.

LAND-1000: %genuine agent

---

ui/src/nav/notifications/useNotifications.ts

notifications: only show dm notifications for talk

---

.github/workflows/deploy-external.yml

ops: deploy kernel with external

---

ui/src/logic/utils.ts

utils: bad hosted check

---

ui/src/logic/utils.ts

utils: dont bail if env not loaded

---

.github/actions/glob/action.yml
.github/helpers/deploy.sh
.github/workflows/bump.yml
.github/workflows/deploy-kernel.yml
.github/workflows/deploy.yml

ops: point to develop as default

---

.github/workflows/deploy-canary.yml
.github/workflows/deploy-external.yml
.github/workflows/deploy-internal.yml
.github/workflows/deploy-kernel.yml
.github/workflows/deploy-live.yml

To match the same system we're using in tloncorp/landscape-apps

ops: switch over to staging workflow
